default: &default
  adapter: postgresql
  encoding: unicode
  pooling:
    pool: 5

development:
  <<: *default
  database: pam_rentz_development
  host: localhost

test:
  <<: *default
  database: pam_rentz_test

production:
  <<: *default
  database: pam_rentz_production

